first version of cutscene engine
jfdoming/Project-B pull request #35
Opened 2020-07-07 00:31 UTC by Telvy

2020-07-07 00:32 UTC, Telvy commented
This is the first version that I managed to commit. Is not exactly what I wanted since most of the system is all show but little substance in the code. I may redo the whole system, but keep certain visual elements like the scrolling text and next icon animation. Thoughts?

2020-07-07 14:46 UTC, rpecka requested changes
Looks like a good start. Since we are a little spread out, it would be nice if we didn't have unused files/code laying around so since you aren't using them yet, can you remove or reformat the json files until the system we talked about is in place?

2020-07-07 14:46 UTC, rpecka commented on cutscene_engine/DialogueBox.gd
> +	#var dialogue : Dictionary = load_dialogue(dialogue_file_path)
Dead code

2020-07-07 14:46 UTC, rpecka commented on cutscene_engine/DialogueBox.gd
> +		#stroheim_tween.interpolate_property(stroheim_pfp, "self_modulate", Color8(1,1,1,0), current_color,0.5,Tween.TRANS_LINEAR,Tween.EASE_OUT)
Dead code

2020-07-17 17:41 UTC, jfdoming commented
Any status update on this?

2020-07-24 19:44 UTC, rpecka commented
> Any status update on this?

Hey, sorry for the late reply. @Telvy is working on a followup to this at the moment. I'm not sure how much of what he is working on now depends on this code but he is new to git so I think the second PR will include everything done in this. We should probably close this.

@Telvy did you use the code in this PR in the new stuff you're working on now? Have you made significant changes to the code in this PR since you submitted it?

2020-07-24 21:21 UTC, Telvy commented
Heyya. Sorry for the late reply. For the past week or so I've been creating a completely new system that has more classes implemented to have the whole system working.

The whole system reads a .json file with information on the respective characters, expressions and lines. Most the code in my first pull request is practically dead at this point. I'll scrap the code for the visual text scrolling affects and that's it.

Also first time comment replying on github. Never did this before but I hope I'm doing this right.

2020-07-24 21:27 UTC, jfdoming commented
@Telvy all good, sounds exciting! Let's close this PR then in favour of the new one.

2020-07-24 21:27 UTC, closed without merging